app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin-app:
    resource: '@AppBundle/Controller/Admin'
    type: annotation

instructor-app:
    resource: '@AppBundle/Controller/Instructor'
    type: annotation

member-app:
    resource: '@AppBundle/Controller/Member'
    type: annotation

logout:
    path: /logout

admin_logout:
    path: /admin/logout
