# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$12$Pgx0sXmjyc4fKjuNJkDyde5Llc47.gHshRAhSNPRg3qauzRcOXNTW
                        roles: 'ROLE_MEMBER'
                    instructor:
                        password: $2y$12$8wsD2fs.Lff3AXtcITHsre4UCHZCZIxrBau5aBlDZuvTum4RfikYC
                        roles: 'ROLE_INSTRUCTOR'
                    admin:
                        password: $2y$12$8wsD2fs.Lff3AXtcITHsre4UCHZCZIxrBau5aBlDZuvTum4RfikYC
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/instructor, roles: ROLE_INSTRUCTOR }
