# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Person:
            algorithm: bcrypt
            cost: 12

    providers:
        users:
            entity:
                class: AppBundle:Person
                property: username

        in_memory:
            memory:
                users:
                    member:
                        password: member
                        roles: 'ROLE_MEMBER'
                    instructor:
                        password: instructor
                        roles: 'ROLE_INSTRUCTOR'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            provider: users
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/instructor, roles: ROLE_INSTRUCTOR }

    role_hierarchy:
        ROLE_INSTRUCTOR: ROLE_MEMBER
        ROLE_ADMIN: ROLE_INSTRUCTOR
