<?php

namespace AppBundle\Form\Type;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MemberType extends AbstractType
{
    public function __construct()
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', TextType::class, [
                'required' => true,
                'label' => 'Voornaam',
            ])
            ->add('lastname', TextType::class, [
                'required' => true,
                'label' => 'Achternaam',
            ])
            ->add('dateofbirth', DateType::class, [
                'required' => true,
                'label' => 'Geboortedatum',
            ])
            ->add('gender', ChoiceType::class, [
                'choices' => [
                    'Man' => 'm',
                    'Vrouw' => 'v',
                    'Beide' => 'speshal',
                    'Geen' => 'geen',
                ],
                'placeholder' => 'Kies een geslacht',
                'label' => 'Geslacht',
            ])
            ->add('adress', TextType::class, [
                'required' => true,
                'label' => 'Adres',
            ])
            ->add('postalcode', TextType::class, [
                'required' => true,
                'label' => 'Postcode',
            ])

            ->add('email', EmailType::class, [
                'required' => true,
                'label' => 'Email adres',
            ])
            ->add('password', PasswordType::class, [
                'required' => true,
                'label' => 'Wachtwoord',
            ])

            ->add('register', SubmitType::class, [
                'label' => 'Registeren',
            ])
        ;
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}